

export const metadata = {
  title: "login",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <section className="login-layout" style={{padding:"5rem 2rem"}}>
      {/* You can add a sidebar, header, etc. */}
      {children}
    </section>
  );
}