import './index.scss'

export const metadata = {
  title: "profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }) {
  return (
    <section className="profile-layout">
      {/* You can add a sidebar, header, etc. */}
      {children}
    </section>
  );
}