import './index.scss'

export const metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <section className="dashboard-layout">
      {/* You can add a sidebar, header, etc. */}
      {children}
    </section>
  );
}