
export const metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <section className="dashboard-layout " style={{padding:"3rem 2rem"}}>
      
      {/* You can add a sidebar, header, etc. */}
      {children}
    </section>
  );
}
